CREATE TABLE phone_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    phone VARCHAR(13) NOT NULL UNIQUE,

    CONSTRAINT pk_phone_data PRIMARY KEY (id),
    CONSTRAINT fk_phone_data_user FOREIGN KEY (user_id) REFERENCES "user"(id),
    CONSTRAINT phone_format_check CHECK (phone ~ '^7\d{10}$')
);

CREATE INDEX idx_phone_data_user_id ON phone_data(user_id);