CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL UNIQUE,
    balance DECIMAL(19, 2) NOT NULL,
    init_balance DECIMAL(19, 2) NOT NULL,

    CONSTRAINT pk_account PRIMARY KEY (id),
    CONSTRAINT fk_account_user FOREIGN KEY (user_id) REFERENCES "user"(id),
    CONSTRAINT balance_positive_check CHECK (balance >= 0)
);

CREATE INDEX idx_account_user_id ON account(user_id);