CREATE TABLE email_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    
    CONSTRAINT pk_email_dta PRIMARY KEY (id),
    CONSTRAINT fk_email_data_user FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE INDEX idx_email_data_user_id ON email_data(user_id);