CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(500) NOT NULL,
    date_of_birth DATE NOT NULL,
    password VARCHAR(500) NOT NULL CHECK (LENGTH(PASSWORD) >= 8),

    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE INDEX idx_user_date_of_birth ON "user" (date_of_birth);
CREATE INDEX idx_user_name ON "user" (name);
CREATE INDEX idx_user_name_date_of_birth ON "user" (name, date_of_birth);